services:
  redis:
    image: redis:7-alpine
    container_name: geo-redis
    restart: unless-stopped
    ports:
      - '127.0.0.1:6379:6379'
    command: ['redis-server', '--save', '60', '1000', '--appendonly', 'no']
    volumes:
      - redis-data:/data

  postgres:
    image: postgres:16-alpine
    container_name: geo-postgres
    restart: unless-stopped
    ports:
      - '127.0.0.1:5432:5432'
    environment:
      POSTGRES_USER: geo
      POSTGRES_PASSWORD: geo
      POSTGRES_DB: geo
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  redis-data:
  postgres-data:
