services:
  redis:
    image: redis:7-alpine
    container_name: geo-redis
    restart: unless-stopped
    ports:
      - '127.0.0.1:6379:6379'
    command: ['redis-server', '--save', '60', '1000', '--appendonly', 'no']
    volumes:
      - redis-data:/data

volumes:
  redis-data:
